export const contractDtoNames = [
  "CleanupArchiveDryRunResponse",
  "CleanupArchiveExecuteResponse",
  "CleanupHiddenDryRunResponse",
  "CleanupHiddenExecuteResponse",
  "GrokDeletePreview",
  "GrokDeleteRequest",
  "GrokDetailResponse",
  "GrokListRequest",
  "GrokListResponse",
  "GrokMutationResponse",
  "GrokRenameRequest",
  "GrokSessionRequest",
  "JobsDetailResponse",
  "JobsListResponse",
  "NoRequest",
  "ProbeBarkTestResponse",
  "ProbeEventsResponse",
  "ProbeInstallHooksResponse",
  "ProbeLogsDbDryRunResponse",
  "ProbeLogsDbExecuteResponse",
  "ProbeLogsDbStatusResponse",
  "ProbeSettingsGetResponse",
  "ProbeSettingsSaveRequest",
  "ProbeSettingsSaveResponse",
  "ProbeStatusResponse",
  "SystemPlatformResponse",
  "SystemProvidersResponse",
  "SystemStatusResponse",
  "SystemVersionResponse",
  "ThreadEventsResponse",
  "ThreadsArchiveResponse",
  "ThreadsBlocksResponse",
  "ThreadsDetailResponse",
  "ThreadsListResponse",
  "ThreadsRenameResponse",
  "ThreadsRestoreResponse",
  "UpdatesCheckResponse",
  "UpdatesInstallResponse",
  "UpdatesStatusResponse"
] as const;

export type ContractDtoName = (typeof contractDtoNames)[number];

export const contractDtoNameSet = new Set<string>(contractDtoNames);
