export const contractDtoNames = [
  "PlanSaveRequest",
  "PlanSaveResult",
  "RemoteConnectionView",
  "RemoteConnectionCredentials",
  "RemoteRevisionRequest",
  "RemoteSelectionRequest",
  "RemoteInvokeRequest",
  "RemoteInvokeResponse",

  "SessionAttachmentRequest",
  "SessionAttachmentResponse",
  "SessionSearchRequest",
  "SessionSearchResponse",
  "SessionBatchRequest",
  "SessionBatchPreview",
  "SessionBatchExecuteRequest",
  "SessionBatchResult",
  "CleanupArchiveDryRunResponse",
  "CleanupArchiveExecuteResponse",
  "CleanupHiddenDryRunResponse",
  "CleanupHiddenExecuteResponse",
  "GrokDeletePreview",
  "GrokDeleteRequest",
  "GrokDetailResponse",
  "GrokListRequest",
  "GrokListResponse",
  "GrokMutationResponse",
  "GrokRenameRequest",
  "GrokSessionRequest",
  "PiDeletePreview",
  "ClaudeDeletePreview",
  "PiDeleteRequest",
  "ClaudeDeleteRequest",
  "PiDetailResponse",
  "ClaudeDetailResponse",
  "PiListRequest",
  "ClaudeListRequest",
  "PiListResponse",
  "ClaudeListResponse",
  "PiMutationResponse",
  "ClaudeMutationResponse",
  "PiRenameRequest",
  "ClaudeRenameRequest",
  "PiSessionRequest",
  "ClaudeSessionRequest",
  "ClaudeDetailRequest",
  "JobsDetailResponse",
  "JobsListResponse",
  "NoRequest",
  "ProbeBarkTestResponse",
  "ProbeEventsResponse",
  "ProbeInstallHooksResponse",
  "ProbeSettingsGetResponse",
  "ProbeSettingsSaveRequest",
  "ProbeSettingsSaveResponse",
  "ProbeStatusResponse",
  "SystemPlatformResponse",
  "SystemProvidersResponse",
  "SystemCapabilitiesResponse",
  "SystemVersionResponse",
  "ThreadsArchiveResponse",
  "ThreadsBlocksResponse",
  "ThreadsDetailResponse",
  "ThreadsListResponse",
  "ThreadsRenameResponse",
  "ThreadsRestoreResponse",
  "UpdatesCheckResponse",
  "UpdatesInstallResponse",
  "UpdatesStatusResponse"
] as const;

export type ContractDtoName = (typeof contractDtoNames)[number];

export const contractDtoNameSet = new Set<string>(contractDtoNames);
