pub const CONTRACT_DTO_NAMES: &[&str] = &[
    "CleanupArchiveDryRunResponse",
    "CleanupArchiveExecuteResponse",
    "CleanupHiddenDryRunResponse",
    "CleanupHiddenExecuteResponse",
    "GrokDeletePreview",
    "GrokDeleteRequest",
    "GrokDetailResponse",
    "GrokListRequest",
    "GrokListResponse",
    "GrokMutationResponse",
    "GrokRenameRequest",
    "GrokSessionRequest",
    "JobsDetailResponse",
    "JobsListResponse",
    "NoRequest",
    "ProbeBarkTestResponse",
    "ProbeEventsResponse",
    "ProbeInstallHooksResponse",
    "ProbeLogsDbDryRunResponse",
    "ProbeLogsDbExecuteResponse",
    "ProbeLogsDbStatusResponse",
    "ProbeSettingsGetResponse",
    "ProbeSettingsSaveRequest",
    "ProbeSettingsSaveResponse",
    "ProbeStatusResponse",
    "SystemPlatformResponse",
    "SystemProvidersResponse",
    "SystemStatusResponse",
    "SystemVersionResponse",
    "ThreadEventsResponse",
    "ThreadsArchiveResponse",
    "ThreadsBlocksResponse",
    "ThreadsDetailResponse",
    "ThreadsListResponse",
    "ThreadsRenameResponse",
    "ThreadsRestoreResponse",
    "UpdatesCheckResponse",
    "UpdatesInstallResponse",
    "UpdatesStatusResponse",
];

pub const CONTRACT_DTO_OWNER_NAMES: &[&str] = &[
    "cleanup", "grok", "jobs", "probe", "system", "threads", "updates",
];
